version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app1

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user
      interpreter: "bash"

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
      interpreter: "bash"
