name: Push Docker Image to ECR (main only)

on:
  push:
    branches: [main]

env:
  AWS_REGION: ap-northeast-2
  ACCOUNT_ID: 115313776476
  REPO_NAME: specranking-backend-main
  TAG: prod

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "TAG=main-${SHORT_SHA}" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Spring Boot JAR
        run: ./gradlew clean build -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          IMAGE="${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.REPO_NAME }}:${{ env.TAG }}"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Output image info
        run: |
          echo "Image pushed: ${{ env.REPO_NAME }}:${{ env.TAG }}"
